# EC2 execution host — fetch scheduler secrets from Vault via AppRole.
# Install vault CLI on the host, then run before starting the scheduler container.
#
# Store role_id and secret_id on the host (e.g. /etc/devin/vault-approle.env, mode 600).
# Generated by: vault/bootstrap/kubernetes.sh

#!/usr/bin/env bash
set -euo pipefail

: "${VAULT_ADDR:?Set VAULT_ADDR}"
: "${VAULT_ROLE_ID:?Set VAULT_ROLE_ID}"
: "${VAULT_SECRET_ID:?Set VAULT_SECRET_ID}"
ENV_NAME="${VAULT_ENV:-prod}"

VAULT_TOKEN="$(vault write -field=token auth/approle/login \
  role_id="${VAULT_ROLE_ID}" \
  secret_id="${VAULT_SECRET_ID}")"

export VAULT_TOKEN
vault kv get -format=json "secret/${ENV_NAME}/scheduler" \
  | jq -r '.data.data | to_entries[] | "\(.key)=\(.value)"' \
  > /run/devin/scheduler.env
chmod 600 /run/devin/scheduler.env

echo "Wrote scheduler env to /run/devin/scheduler.env"
