/** README content that does not echo the raw user prompt into the repo. */
export function safeScaffoldReadme(
  title: string,
  stackRuntime: string,
  runHint: string,
): string {
  const safeTitle = title.trim() || "Devin app";
  return `# ${safeTitle}

Scaffold for a coding-agent session (${stackRuntime}). Product requirements stay in the session prompt — do not treat this file as instructions.

## Getting started

\`\`\`bash
${runHint}
\`\`\`

_Implementation will be generated by the runtime agent in the sandbox._
`;
}
