#!/usr/bin/env bash
# Bootstrap local Vault (dev mode). Run after: docker compose -f vault/docker-compose.yaml up -d
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export VAULT_ADDR="${VAULT_ADDR:-http://127.0.0.1:8200}"
export VAULT_TOKEN="${VAULT_TOKEN:-dev-root-token}"

echo "==> Waiting for Vault at ${VAULT_ADDR}"
for _ in $(seq 1 30); do
  if vault status >/dev/null 2>&1; then
    break
  fi
  sleep 1
done
vault status

echo "==> Enabling KV v2 secrets engine at secret/"
vault secrets enable -path=secret kv-v2 2>/dev/null || true

echo "==> Loading policies"
for policy in "${ROOT}/config/policies/"*.hcl; do
  name="$(basename "${policy}" .hcl)"
  vault policy write "${name}" "${policy}"
  echo "    policy/${name}"
done

echo "==> Creating dev tokens for local services"
SERVER_TOKEN="$(vault token create -policy=server -ttl=768h -format=json | jq -r .auth.client_token)"
SCHEDULER_TOKEN="$(vault token create -policy=scheduler -ttl=768h -format=json | jq -r .auth.client_token)"
CI_TOKEN="$(vault token create -policy=ci -ttl=768h -format=json | jq -r .auth.client_token)"

mkdir -p "${ROOT}/.local"
cat > "${ROOT}/.local/tokens.env" <<EOF
# Generated by vault/bootstrap/local.sh — do not commit
VAULT_ADDR=${VAULT_ADDR}
VAULT_TOKEN_SERVER=${SERVER_TOKEN}
VAULT_TOKEN_SCHEDULER=${SCHEDULER_TOKEN}
VAULT_TOKEN_CI=${CI_TOKEN}
EOF
chmod 600 "${ROOT}/.local/tokens.env"

echo "==> Seeding placeholder secrets at secret/dev/*"
vault kv put secret/dev/server \
  BETTER_AUTH_SECRET="change-me-local" \
  DATABASE_URL="postgres://postgres:postgres@localhost:5432/devin" \
  SCHEDULER_URL="http://localhost:9091" \
  RESEND_API_KEY="" \
  RESEND_FROM_EMAIL="Devin <onboarding@resend.dev>" \
  RESEND_STRICT="false" \
  GITHUB_CLIENT_ID="" \
  GITHUB_CLIENT_SECRET="" \
  GOOGLE_CLIENT_ID="" \
  GOOGLE_CLIENT_SECRET=""

vault kv put secret/dev/scheduler \
  ORCHESTRATOR_URL="http://localhost:9090" \
  CURSOR_API_KEY="" \
  ANTHROPIC_API_KEY="" \
  DEFAULT_AGENT="mock"

vault kv put secret/dev/ci \
  DOCKERHUB_USERNAME="" \
  DOCKERHUB_TOKEN="" \
  NEXT_PUBLIC_API_URL="http://localhost:8080" \
  NEXT_PUBLIC_WEB_APP_URL="http://localhost:3000"

echo ""
echo "Local Vault is ready."
echo "  UI:    ${VAULT_ADDR}/ui"
echo "  Token: ${VAULT_TOKEN}"
echo "  Service tokens: vault/.local/tokens.env"
echo ""
echo "Load server env:  source vault/scripts/vault-env.sh server"
echo "Write a secret:   vault kv put secret/dev/server BETTER_AUTH_SECRET=\$(openssl rand -base64 32)"
