import type { StackRuntime } from "@devin/types";
import { buildHeuristicDraftPlan } from "./draft-planner.js";
import {
  scaffoldFilesFromDraft,
  type ScaffoldFile,
} from "./scaffold-from-draft.js";

function gitignoreForStack(stack: StackRuntime): string {
  const common = "node_modules/\n.env\n.DS_Store\n";
  switch (stack) {
    case "go":
      return `${common}bin/\n*.exe\n`;
    case "rust":
      return `${common}target/\n`;
    case "python":
      return `${common}__pycache__/\n.venv/\n*.pyc\n`;
    case "nextjs":
      return `${common}.next/\ndist/\n`;
    case "node":
    default:
      return common;
  }
}

function goShellFiles(title: string): ScaffoldFile[] {
  const moduleName =
    title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "")
      .slice(0, 24) || "devinapp";

  return [
    {
      path: "go.mod",
      content: `module example.com/${moduleName}\n\ngo 1.23\n`,
    },
    {
      path: "main.go",
      content: `package main

import (
  "encoding/json"
  "log"
  "net/http"
  "os"
)

func main() {
  mux := http.NewServeMux()
  mux.HandleFunc("/health", func(w http.ResponseWriter, _ *http.Request) {
    w.Header().Set("Content-Type", "application/json")
    _ = json.NewEncoder(w).Encode(map[string]bool{"ok": true})
  })

  port := os.Getenv("PORT")
  if port == "" {
    port = "3000"
  }
  log.Printf("listening on :%s", port)
  log.Fatal(http.ListenAndServe(":"+port, mux))
}
`,
    },
  ];
}

function rustShellFiles(title: string): ScaffoldFile[] {
  const crateName =
    title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "")
      .slice(0, 24) || "devin-app";

  return [
    {
      path: "Cargo.toml",
      content: `[package]
name = "${crateName}"
version = "0.1.0"
edition = "2021"

[dependencies]
`,
    },
    {
      path: "src/main.rs",
      content: `fn main() {
    println!("${title} — scaffold ready");
}
`,
    },
  ];
}

function pythonShellFiles(): ScaffoldFile[] {
  return [
    {
      path: "app.py",
      content: `from flask import Flask, jsonify

app = Flask(__name__)

@app.get("/health")
def health():
    return jsonify(ok=True)

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=int(__import__("os").environ.get("PORT", 3000)))
`,
    },
    {
      path: "requirements.txt",
      content: "flask>=3.0.0\n",
    },
  ];
}

function readmeForShell(
  title: string,
  prompt: string,
  stack: StackRuntime,
): string {
  const runHint =
    stack === "go"
      ? "go run ."
      : stack === "rust"
        ? "cargo run"
        : stack === "python"
          ? "pip install -r requirements.txt && python app.py"
          : "npm install && npm start";

  return `# ${title}

${prompt}

## Getting started

\`\`\`bash
${runHint}
\`\`\`

_Implementation will be generated by the runtime agent in the sandbox._
`;
}

export function greenfieldShellScaffoldFiles(opts: {
  title: string;
  prompt: string;
  stackRuntime: StackRuntime;
}): ScaffoldFile[] {
  const readme: ScaffoldFile = {
    path: "README.md",
    content: readmeForShell(opts.title, opts.prompt, opts.stackRuntime),
  };
  const gitignore: ScaffoldFile = {
    path: ".gitignore",
    content: gitignoreForStack(opts.stackRuntime),
  };

  if (opts.stackRuntime === "node" || opts.stackRuntime === "nextjs") {
    const plan = buildHeuristicDraftPlan({ prompt: opts.prompt });
    const nodeFiles = scaffoldFilesFromDraft(plan, {
      title: opts.title,
      prompt: opts.prompt,
    });
    const paths = new Set(nodeFiles.map((file) => file.path));
    if (!paths.has("README.md")) {
      nodeFiles.unshift(readme);
    } else {
      const index = nodeFiles.findIndex((file) => file.path === "README.md");
      if (index >= 0) {
        nodeFiles[index] = readme;
      }
    }
    if (!paths.has(".gitignore")) {
      nodeFiles.push(gitignore);
    }
    return nodeFiles;
  }

  const stackFiles =
    opts.stackRuntime === "go"
      ? goShellFiles(opts.title)
      : opts.stackRuntime === "rust"
        ? rustShellFiles(opts.title)
        : pythonShellFiles();

  return [readme, gitignore, ...stackFiles];
}
